app/models/user.py
from flask_login import UserMixin
from app import db

class User(UserMixin, db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.Integer, nullable=False)
    name = db.Column(db.String(40), nullable=False)
    username = db.Column(db.String(20), nullable=False, unique=True)
    password = db.Column(db.String(128), nullable=False)
    role = db.Column(db.String(5),nullable=False)   # user or admin

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_injector import inject
from app.services.author import AuthorService
from app.services.user import UserService
from flask_login import login_required
from app.forms.login_form import LoginForm
from app.forms.signup_form import SignupForm
from app.forms.author.delete import DeleteForm
from app.forms.user.promote import PromoteForm
from flask_login import current_user

auth = Blueprint("auth", __name__)

@auth.route("/profile")
@login_required
def profile():
    author = current_user
    print(author.username)
    return render_template("/author/profile.html", author=author)



@auth.route("/login", methods=["GET", "POST"])
@inject
def login(author_service: AuthorService):
    load = 2
    login_form = LoginForm()

    error_message = ""

    if login_form.validate_on_submit():
        if author_service.login(login_form.username.data, login_form.password.data):

            return redirect(url_for("auth.profile"))

        error_message = "incorrect username or password"

    return render_template("author/loginauthor.html", form=login_form, error_message=error_message)

@auth.route("/logout")
@login_required
@inject
def logout(author_service: AuthorService):
    author_service.logout()
    
    return redirect(url_for("dashboard.home"))

@auth.route("/delete", methods=["GET","POST"])
@inject
def delete(author_service: AuthorService):
    delete_form = DeleteForm()
    error_message = ""

    if delete_form.validate_on_submit():
       print("Deleting")
       author = author_service.get_by_username(delete_form.username.data)
       if(author):
        author_service.delete(
            author
            )

       return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("author/delete.html", form=delete_form, error_message=error_message)


@auth.route("/promotetoAuthor", methods=["GET","POST"])
@inject
def promotetoAuthor(user_service: UserService,author_service: AuthorService):
    promote_form = PromoteForm()
    error_message = ""

    if promote_form.validate_on_submit():

        print("Promoting")
        user = user_service.get_by_username(promote_form.username.data)
        if(user):
            author_service.create(name=user.name, username=user.username, password=user.password)
            user_service.delete(user)

            return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/promoteAuthor.html", form=promote_form, error_message=error_message)

app/routes/user.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required
from flask_injector import inject
from app.services.user import UserService
from app.forms.login_form import LoginForm
from app.forms.signup_form import SignupForm
from app.forms.user.delete import DeleteForm
from app.forms.user.promote import PromoteForm


user = Blueprint("user", __name__)

@user.route("/profile")
@login_required
def profile():
    return render_template("/user/profile.html")

@user.route("/signup", methods=["GET", "POST"])
@inject
def signup(user_service: UserService):
    signup_form = SignupForm()

    if signup_form.validate_on_submit():
        if not user_service.get_by_username(username=signup_form.username.data):
            user_service.signup(
                signup_form.name.data,
                signup_form.username.data,
                signup_form.password.data
            )

        return redirect(url_for("user.login"))

    return render_template("signup.html", form=signup_form)

@user.route("/login", methods=["GET", "POST"])
@inject
def login(user_service: UserService):
    
    login_form = LoginForm()

    error_message = ""


    if login_form.validate_on_submit():
        if user_service.login(login_form.username.data, login_form.password.data):
            

            return redirect(url_for("user.profile"))

        error_message = "incorrect username or password"

    return render_template("login.html", form=login_form, error_message=error_message)

@user.route("/logout")
@login_required
@inject
def logout(user_service: UserService):
    user_service.logout()
    
    return redirect(url_for("dashboard.home"))

@user.route("/delete", methods=["GET","POST"])
@inject
def delete(user_service: UserService):
    delete_form = DeleteForm()
    error_message = ""
    print(delete_form.errors)
    if delete_form.validate_on_submit():
       print("Deleting")
       user = user_service.get_by_username(delete_form.username.data)
       if(user):
        user_service.delete(
            user
            )

        return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/delete.html", form=delete_form, error_message=error_message)

@user.route("/promotetoAdmin", methods=["GET","POST"])
@inject
def promotetoAdmin(user_service: UserService):
    promote_form = PromoteForm()
    error_message = ""

    if promote_form.validate_on_submit():
        
        print("Promoting")
        user = user_service.get_by_username(promote_form.username.data)
        if(user):

            user_service.promote(user)
            return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/promote.html", form=promote_form, error_message=error_message)

app/templates/user/delete.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Login {% endblock %}

{% block container %}
    <form action="{{ url_for('user.delete') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}
        {{ form.csrf_token }}

        {{ wtf.form_field(form.username) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary mr-5">Delete</button>
    </form>
{% endblock %}

app/templates/user/profile.html
{% extends "layout.html" %}

{% block page_title %} Profile {% endblock %}

{% block container %}
    <div class="d-flex flex-row justify-content-between mb-5">
        <h1>Profile</h1>
        <div class="d-flex flex-row gap-3 text-light">
            <a class="btn btn-danger ml-3 mt-auto mb-auto" href="{{ url_for("user.logout") }}">
                Logout
            </a>
        </div>
    </div>
    <div>
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" value="{{ current_user.name }}" disabled>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Username</label>
            <input type="text" class="form-control" id="price" value="{{ current_user.username }}" disabled>
        </div>
    </div>
{% endblock %}

app/templates/user/promote.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Login {% endblock %}

{% block container %}
    <form action="{{ url_for('user.promotetoAdmin') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}
        {{ form.csrf_token }}

        {{ wtf.form_field(form.username) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary mr-5">Promote</button>
    </form>
{% endblock %}

app/templates/user/promoteAuthor.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Login {% endblock %}

{% block container %}
    <form action="{{ url_for('auth.promotetoAuthor') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}
        {{ form.csrf_token }}

        {{ wtf.form_field(form.username) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary mr-5">Promote</button>
    </form>
{% endblock %}