app/models/post.py
from flask_sqlalchemy import SQLAlchemy
from app import db
from datetime import datetime
from flask_login import UserMixin


class Post(UserMixin, db.Model):
    __tablename__ = "post"

    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.Integer, nullable=False)
    title = db.Column(db.String(20), nullable=False, unique=True)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.String, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey("author.id"), nullable=False)

app/routes/posts.py
from flask import Blueprint, render_template, redirect, url_for, jsonify
from flask_injector import inject
from app.services.posts import Postservice
from app.forms.posts.create_form import CreateForm
from app.forms.posts.edit_form import EditForm
from flask_login import current_user


posts = Blueprint("posts", __name__)

@posts.route("/")
@inject
def list_all(post_service: Postservice):
    return render_template("posts/list.html", posts=post_service.get_all())

@posts.route("/create")
def create():
    return render_template("/posts/create.html", form=CreateForm())

@posts.route("/", methods=["POST"])
@inject
def store(post_service: Postservice):
    create_form = CreateForm()

    if create_form.validate_on_submit():
        post_service.create(
            title=create_form.title.data,
            content=create_form.content.data,
            id = current_user.id
        )

        return redirect(url_for("posts.list_all"))

    return render_template("/posts/create.html", form=create_form)

@posts.route("/<public_id>")
@inject
def view(post_service: Postservice, public_id):
    post = post_service.get_by_public_id(public_id)

    if not post:
        return redirect(url_for("posts.list_all"))

    return render_template("posts/view.html", post=post)

@posts.route("/<public_id>/edit")
@inject
def edit(post_service: Postservice, public_id):
    post = post_service.get_by_public_id(public_id)

    if not post:
        return redirect(url_for("posts.list_all"))

    edit_form = EditForm()
    edit_form.title.data = post.title
    edit_form.content.data = post.content
    

    return render_template("posts/edit.html", form=edit_form, post=post)

@posts.route("/<public_id>", methods=["POST"])
@inject
def update(post_service: Postservice, public_id):
    post = post_service.get_by_public_id(public_id)

    if not post:
        return redirect(url_for("posts.list_all"))

    edit_form = EditForm()

    if edit_form.validate_on_submit():
        post_service.update(
            post,
            edit_form.title.data ,
            edit_form.content.data 
        )

        return redirect(url_for("posts.list_all"))

    return render_template("posts/view.html", post=post)

@posts.route("/<public_id>", methods=["DELETE"])
@inject
def delete(post_service: Postservice, public_id):
    post = post_service.get_by_public_id(public_id)

    if post:
        post_service.delete(post)

    return jsonify({"msg": "post deleted successfully"})

app/templates/posts/create.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Create post {% endblock %}

{% block container %}
    <form action="{{ url_for('posts.store') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}

        {{ wtf.form_field(form.title) }}
        {{ wtf.form_field(form.content) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary">Create</button>
    </form>
{% endblock %}

app/templates/posts/edit.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Edit post {% endblock %}

{% block container %}
    <form action="{{ url_for('posts.update', public_id=post.public_id) }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}

        {{ wtf.form_field(form.title) }}

        {{ wtf.form_field(form.content) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary">Edit</button>
    </form>
{% endblock %}

app/templates/posts/list.html
{% extends "layout.html" %}

{% block page_title %} List posts {% endblock %}

{% block container %}
    <div class="d-flex flex-row justify-content-between">
        <h1>posts List</h1>
        {% if current_user.role == "author" %}
        <a class="btn btn-secondary mt-auto mb-auto" href="{{ url_for("posts.create") }}">
            create new post
        </a>
        {% endif %}
    </div>

    {% if posts %}
        <table class="table table-hover table-light mt-5">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Public ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Date Posted</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ post.public_id }}</td>
                        <td>{{ post.title }}</td>
                        <td>{{ post.datea_posted }}</td>
                        <td>{{ post.content }}</td>
                        {% if current_user.role == "author" or current_user.role == "admin" %}
                            <td>
                                <a href="{{ url_for("posts.view", public_id=post.public_id) }}">View</a>
                            </td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <span>
            No posts available. :(
        </span>
    {% endif %}


{% endblock %}

app/templates/posts/view.html
{% extends "layout.html" %}

{% block page_title %} View post {% endblock %}

{% block container %}
    <div class="d-flex flex-row justify-content-between mb-5">
        <h1>post</h1>
        <div class="d-flex flex-row gap-3 text-light">
            <a class="btn btn-secondary ml-3 mt-auto mb-auto" href="{{ url_for("posts.edit", public_id=post.public_id) }}">
                Edit
            </a>
            <a class="btn btn-danger ml-3 mt-auto mb-auto" onclick="deletepost()">
                Delete
            </a>
        </div>
    </div>
    <div>
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" value="{{ post.title }}" disabled>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" value="{{ post.date_posted }}" disabled>
        </div>
    </div>
    <script>
        const deletepost = () => {
            fetch("{{ url_for('posts.delete', public_id=post.public_id) }}",  {
                method: 'DELETE'
            }).then(response => {
                if (response.ok) {
                    window.location.href = "{{ url_for('posts.list_all') }}";
                }
            }).catch(error => {
                // console.error('Network error:', error);
            });
        }
    </script>
{% endblock %}