app/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length

class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=8, max=20)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20)])

app/forms/signup_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, Regexp

class SignupForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=4, max=40)])
    username = StringField("Username", validators=[DataRequired(), Length(min=8, max=20)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20), Regexp(regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$", message="should contains at least one lowercase letter, one uppercase letter, and one digit")])

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_injector import inject
from app.services.author import AuthorService
from app.services.user import UserService
from flask_login import login_required
from app.forms.login_form import LoginForm
from app.forms.signup_form import SignupForm
from app.forms.author.delete import DeleteForm
from app.forms.user.promote import PromoteForm
from flask_login import current_user

auth = Blueprint("auth", __name__)

@auth.route("/profile")
@login_required
def profile():
    author = current_user
    print(author.username)
    return render_template("/author/profile.html", author=author)



@auth.route("/login", methods=["GET", "POST"])
@inject
def login(author_service: AuthorService):
    load = 2
    login_form = LoginForm()

    error_message = ""

    if login_form.validate_on_submit():
        if author_service.login(login_form.username.data, login_form.password.data):

            return redirect(url_for("auth.profile"))

        error_message = "incorrect username or password"

    return render_template("author/loginauthor.html", form=login_form, error_message=error_message)

@auth.route("/logout")
@login_required
@inject
def logout(author_service: AuthorService):
    author_service.logout()
    
    return redirect(url_for("dashboard.home"))

@auth.route("/delete", methods=["GET","POST"])
@inject
def delete(author_service: AuthorService):
    delete_form = DeleteForm()
    error_message = ""

    if delete_form.validate_on_submit():
       print("Deleting")
       author = author_service.get_by_username(delete_form.username.data)
       if(author):
        author_service.delete(
            author
            )

       return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("author/delete.html", form=delete_form, error_message=error_message)


@auth.route("/promotetoAuthor", methods=["GET","POST"])
@inject
def promotetoAuthor(user_service: UserService,author_service: AuthorService):
    promote_form = PromoteForm()
    error_message = ""

    if promote_form.validate_on_submit():

        print("Promoting")
        user = user_service.get_by_username(promote_form.username.data)
        if(user):
            author_service.create(name=user.name, username=user.username, password=user.password)
            user_service.delete(user)

            return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/promoteAuthor.html", form=promote_form, error_message=error_message)

app/routes/user.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required
from flask_injector import inject
from app.services.user import UserService
from app.forms.login_form import LoginForm
from app.forms.signup_form import SignupForm
from app.forms.user.delete import DeleteForm
from app.forms.user.promote import PromoteForm


user = Blueprint("user", __name__)

@user.route("/profile")
@login_required
def profile():
    return render_template("/user/profile.html")

@user.route("/signup", methods=["GET", "POST"])
@inject
def signup(user_service: UserService):
    signup_form = SignupForm()

    if signup_form.validate_on_submit():
        if not user_service.get_by_username(username=signup_form.username.data):
            user_service.signup(
                signup_form.name.data,
                signup_form.username.data,
                signup_form.password.data
            )

        return redirect(url_for("user.login"))

    return render_template("signup.html", form=signup_form)

@user.route("/login", methods=["GET", "POST"])
@inject
def login(user_service: UserService):
    
    login_form = LoginForm()

    error_message = ""


    if login_form.validate_on_submit():
        if user_service.login(login_form.username.data, login_form.password.data):
            

            return redirect(url_for("user.profile"))

        error_message = "incorrect username or password"

    return render_template("login.html", form=login_form, error_message=error_message)

@user.route("/logout")
@login_required
@inject
def logout(user_service: UserService):
    user_service.logout()
    
    return redirect(url_for("dashboard.home"))

@user.route("/delete", methods=["GET","POST"])
@inject
def delete(user_service: UserService):
    delete_form = DeleteForm()
    error_message = ""
    print(delete_form.errors)
    if delete_form.validate_on_submit():
       print("Deleting")
       user = user_service.get_by_username(delete_form.username.data)
       if(user):
        user_service.delete(
            user
            )

        return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/delete.html", form=delete_form, error_message=error_message)

@user.route("/promotetoAdmin", methods=["GET","POST"])
@inject
def promotetoAdmin(user_service: UserService):
    promote_form = PromoteForm()
    error_message = ""

    if promote_form.validate_on_submit():
        
        print("Promoting")
        user = user_service.get_by_username(promote_form.username.data)
        if(user):

            user_service.promote(user)
            return redirect(url_for("dashboard.home"))
       
    print("no Deleting")
    return render_template("user/promote.html", form=promote_form, error_message=error_message)

app/templates/index.html
{% extends "layout.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block page_title %} Home {% endblock %}

{% block container %}
<h1>Example Flask Application</h1>
<h2>
    {% if current_user %}
        Welcome {{ current_user.name }}
    {% else %}
        Welcome to the Our Website
    {% endif  %}
</h2>
<p> 
    {% if current_user.role == "admin" %}
    <div class="d-flex flex-row justify-content-between">
        <h1>User Managment</h1>

        <a class="nav-item nav-link {% if request.path == url_for('user.delete') %}active{% endif %}" href="{{ url_for('user.delete') }}">
            Delete User
        </a>

        <a class="nav-item nav-link {% if request.path == url_for('auth.delete') %}active{% endif %}" href="{{ url_for('auth.delete') }}">
        Delete Author
        </a>

        <a class="nav-item nav-link {% if request.path == url_for('user.promotetoAdmin') %}active{% endif %}" href="{{ url_for('user.promotetoAdmin') }}">
            Promote to Admin
        </a>

        <a class="nav-item nav-link {% if request.path == url_for('auth.promotetoAuthor') %}active{% endif %}" href="{{ url_for('auth.promotetoAuthor') }}">
            Promote to Author
        </a>
    </div>

    {% endif %}
</p>
{% endblock %}

app/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en"{% endblock %}

{% block title %}
  {% block page_title %}{% endblock %} | Flask Starter Structure
{% endblock %}

{% block metas %}
{{super()}}

<meta charset="UTF-8">
<link rel="icon" href="/favicon.ico">
{% endblock %}

{% block styles %}
    {{super()}}

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block navbar %}
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand mr-5" href="#">Flask Starter Structure</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex flex-row justify-content-between w-100">
      <div class="d-flex flex-row">
        <a class="nav-item nav-link {% if request.path == url_for('dashboard.home') %}active{% endif %}" href="{{ url_for('dashboard.home') }}">
          Home <span class="sr-only">(current)</span>
        </a>
        <a class="nav-item nav-link {% if request.path == url_for('posts.list_all') %}active{% endif %}" href="{{ url_for('posts.list_all') }}">
          posts
        </a>
      </div>
      <div class="d-flex flex-row">
        {% if not current_user.is_authenticated %}
          <a class="nav-item nav-link {% if request.path == url_for('user.login') %}active{% endif %}" href="{{ url_for('user.login') }}">
            Login
          </a>
          <a class="nav-item nav-link {% if request.path == url_for('auth.login') %}active{% endif %}" href="{{ url_for('auth.login') }}">
            Login Author
          </a>
          <a class="nav-item nav-link {% if request.path == url_for('user.signup') %}active{% endif %}" href="{{ url_for('user.signup') }}">
            Signup
          </a>
        {% else %}
          <a class="nav-item nav-link {% if request.path == url_for('user.profile') %}active{% endif %}" href="{{ url_for('user.profile') }}">
            Profile
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<div class="app container mt-5">
    {% block container %}
    {% endblock %}
</div>
{% endblock %}

app/templates/login.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Login {% endblock %}

{% block container %}
    <form action="{{ url_for('user.login') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}

        {{ wtf.form_field(form.username) }}
        {{ wtf.form_field(form.password) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary mr-5">Login</button>
        <a href="{{ url_for('user.signup') }}">Don't have an account? Signup</a>
    </form>
{% endblock %}

app/templates/signup.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Signup {% endblock %}

{% block container %}
    <form action="{{ url_for('user.signup') }}" method="POST" class="form" role="form">
        {{ form.hidden_tag() }}

        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.username) }}
        {{ wtf.form_field(form.password) }}

        {{ wtf.form_errors(form, hiddens="only") }}

        <button type="submit" class="btn btn-secondary mr-5">Signup</button>
        <a href="{{ url_for('user.login') }}">Already have an account? Login</a>
    </form>
{% endblock %}